Controllers/CourseController.cs
using ILEARN.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using System.Linq;
using System.Text;

namespace ILEARN.Controllers
{
    public class CourseController : Controller
    {
        public IActionResult Index(int? page)
        {
            using IlearnDbContext db = new();
            //var pageSize = 20;
            //var pageIndex = page ?? 1;
            var items = db.Courses.OrderBy(x => x.Id).ToList();
            return View(items);
        }

        public IActionResult GetCourse(int ID)
        {
            using IlearnDbContext db = new();
            var course = db.Courses.FirstOrDefault(m => m.Id == ID);
            if (course == null)
            {
                return RedirectToAction("NullPage", "Error");
            }
            else
            {
                return View(course);
            }
        }

        public IActionResult PriceIncreased(int? page)
        {
            using IlearnDbContext db = new();
            //var pageSize = 20;
            //var pageIndex = page ?? 1;
            var items = db.Courses.OrderBy(x => x.CoursePrice).ToList();
            return View(items);
        }

        public IActionResult PriceDecreased(int? page)
        {
            using IlearnDbContext db = new();
            //var pageSize = 20;
            //var pageIndex = page ?? 1;
            var items = db.Courses.OrderByDescending(x => x.CoursePrice).ToList();
            return View(items);
        }

        [HttpGet]
        public IActionResult Search(string search, int? page)
        {
            using IlearnDbContext db = new();
            //var pageSize = 20;
            //var pageIndex = page ?? 1;
            var items = db.Courses
                .AsEnumerable()
                .Where(c => RemoveDiacritics(c.CourseName.ToLower()).Contains(RemoveDiacritics(search.ToLower())))
                .OrderBy(c => c.Id)
                .ToList();
            TempData["count"] = items.Count;
            TempData["value"] = search;
            return View(items);
        }

        private static string RemoveDiacritics(string text)
        {
            var normalizedString = text.Normalize(NormalizationForm.FormD);
            var stringBuilder = new System.Text.StringBuilder();

            foreach (char c in normalizedString)
            {
                var unicodeCategory = CharUnicodeInfo.GetUnicodeCategory(c);
                if (unicodeCategory != UnicodeCategory.NonSpacingMark)
                {
                    stringBuilder.Append(c);
                }
            }

            return stringBuilder.ToString().Normalize(NormalizationForm.FormC);
        }

        public bool FunctionCheck(int functionID)
        {
            using IlearnDbContext db = new();
            var userName = TempData["user"]?.ToString()?.Trim();
            var gv = db.Accounts.First(item => item.Username == userName);
            if (gv != null)
            {
                int count = db.Decentralizations.Count(m => m.AccountId == gv.Id && m.FunctionId == functionID);
                if (count == 0)
                {
                    //báo không có quyền
                    return false;
                }
                else
                {
                    return true;
                }
            }

            return false;
        }

        public IActionResult CourseList()
        {
            if (FunctionCheck(5) == false)
            {
                //báo không có quyền
                return RedirectToAction("NoPrivilege", "Error");
            }

            using IlearnDbContext db = new IlearnDbContext();
            var courseList = db.Courses.Include(c => c.Lecturer).Include(c => c.Category).ToList();
            return View(courseList);
        }

        public IActionResult AddCourse()
        {
            if (FunctionCheck(6) == false)
            {
                //báo không có quyền
                return RedirectToAction("NoPrivilege", "Error");
            }

            return View();
        }

        [HttpPost]
        public IActionResult AddNewCourse(string name, decimal price, decimal discountPrice, int discount, int lecturesCount, string introduction, string description, int lecturerID, int categoryID)
        {
            IlearnDbContext db = new();
            Course course = new() { CourseName = name, CoursePrice = price, Description = description, DiscountPrice = discountPrice, Discount = discount, NumberOfLectures = lecturesCount, Introduction = introduction, LecturerId = lecturerID, CategoryId = categoryID };
            db.Courses.Add(course);
            db.SaveChanges();
            TempData["message"] = "Thêm thành công.";
            return RedirectToAction("CourseList");
        }

        public IActionResult UpdateCourse(int ID)
        {
            if (FunctionCheck(7) == false)
            {
                //báo không có quyền
                return RedirectToAction("NoPrivilege", "Error");
            }
            using IlearnDbContext db = new();
            var course = db.Courses.FirstOrDefault(m => m.Id == ID);
            return View(course);
        }

        [HttpPost]
        public IActionResult UpdateCurrentCourse(int ID, string name, decimal price, decimal discountPrice, int discount, int lecturesCount, string introduction, string description, int lecturerID, int categoryID)
        {
            using IlearnDbContext db = new();
            Course course = db.Courses.Find(ID);

            course.CourseName = name;
            course.CoursePrice = price;
            course.DiscountPrice = discountPrice;
            course.Discount = discount;
            course.NumberOfLectures = lecturesCount;
            course.Description = description;
            course.Introduction = introduction;
            course.LecturerId = lecturerID;
            course.CategoryId = categoryID;

            db.SaveChanges();

            TempData["message"] = "Cập nhật thành công.";
            return RedirectToAction("CourseList");
        }

        public IActionResult DeleteCourse(int ID)
        {
            if (FunctionCheck(8) == false)
            {
                //báo không có quyền
                return RedirectToAction("NoPrivilege", "Error");
            }

            using IlearnDbContext db = new();
            var course = db.Courses.Find(ID);
            db.Courses.Remove(course);
            db.SaveChanges();
            TempData["message"] = "Xóa thành công.";
            return RedirectToAction("CourseList");
        }

        public IActionResult MyCourse(int ID)
        {
            using IlearnDbContext db = new();
            var shoppingSession = db.ShoppingSessions.Where(m => m.AccountId == ID).ToList();
            List<int> courseList = new List<int>();
            if (shoppingSession != null)
            {
                foreach (var session in shoppingSession)
                {
                    var courses = db.Carts.Where(m => m.SessionId == session.Id)
                                            .Select(m => m.CourseId)
                                            .ToList();
                    courseList.AddRange(courses);
                }
                return View(courseList);
            }
            return View();
        }

        public IActionResult LearnThroughVideo()
        {
            using IlearnDbContext db = new IlearnDbContext();
            var videoList = db.Videos.Include(m=>m.Course).ToList();
            return View(videoList);
        }
    }
}

Controllers/HomeLecturerController.cs
using ILEARN.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ILEARN.Controllers
{
    public class HomeLecturerController : Controller
    {
        public IActionResult Index() { return View(); }
        public IActionResult CourseList(int ID)
        {
            using IlearnDbContext db = new IlearnDbContext();
            var lecturer = db.Lecturers.FirstOrDefault(m=>m.AccountId == ID);
            var courseList = db.Courses.Include(m=>m.Category).Where(item => item.LecturerId == lecturer.Id).ToList();
            return View(courseList);
        }

        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ChangePassword(string password1, string password2, int ID)
        {
            if (password1 != password2)
            {
                TempData["error"] = "Mật khẩu không trùng nhau";
                return RedirectToAction("ChangePassword");
            }
            using IlearnDbContext db = new IlearnDbContext();
            var account = db.Accounts.Find(ID);
            account.Password = password1;
            db.SaveChanges();
            TempData["message"] = "Cập nhật thành công.";
            return RedirectToAction("Index");
        }
    }
}

Views/HomeLecturer/ChangePassword.cshtml
@model ILEARN.Models.Account

@{
    ViewData["Title"] = "Thay đổi mật khẩu";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Thay đổi mật khẩu</h1>
                <form action="@Url.Action("ChangePassword","HomeLecturer", new {ID = int.Parse(User.FindFirst("id").Value)})" method="post">
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <div class="col-md-2">
                            <label class="label-style">Nhập mật khẩu</label>
                        </div>
                        <div class="col-md-10">
                            <input class="input-style input-lg" type="text" name="password1" placeholder="Nhập mật khẩu..." />
                        </div>
                    </div>
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <div class="col-md-2">
                            <label class="label-style">Nhập lại mật khẩu</label>
                        </div>
                        <div class="col-md-10">
                            <input class="input-style input-lg" type="text" name="password2" placeholder="Nhập lại mật khẩu..."/>
                        </div>
                    </div>
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <p>@TempData["error"]</p>
                    </div>
                    <button class="btn btn-primary" type="submit">Xác nhận</button>
                </form>
            </div>
        </div>
    </div>
</div>

Views/HomeLecturer/CourseList.cshtml
@model List<ILEARN.Models.Course>
@using ILEARN.Models;

@{
    ViewData["Title"] = "Danh sách khóa học";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}


<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

<div id="page-wrapper">
    <div class="container-flush">
        <h2 class="page-header">Danh sách khóa học</h2>
        <div class="row">
            <div class="col-md-12 offset-2">
                <table class="table table-bordered" id="dataTabledata" style="font-size: 12px">
                    <thead>
                        <tr class="text-center">
                            <th>STT</th>
                            <th>Tên khóa học</th>
                            <th>Tên giảng viên</th>
                            <th>Số lượng bài giảng</th>
                            <th>Giá</th>
                            <th>Giá giảm giá</th>
                            <th>Giảm giá</th>
                            <th>Thể loại</th>
                            <th>Giới thiệu</th>
                            <th>Chú thích</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                        }
                        @foreach (var course in Model)
                        {
                            <tr>
                                <td>@i</td>
                                <td>@course.CourseName</td>
                                <td>@course.Lecturer.LecturerName</td>
                                <td>@course.NumberOfLectures</td>
                                <td>@String.Format("{0: #,##0đ}", @course.CoursePrice)</td>
                                <td>@String.Format("{0: #,##0đ}", @course.DiscountPrice)</td>
                                <td>@course.Discount</td>
                                <td>@course.Category.CategoryName</td>
                                <td>@course.Introduction</td>
                                <td>@course.Description</td>
                                <td>
                                    <a class="btn btn-info" href="@Url.Action("UpdateCourse","Course",new {ID = course.Id})">Sửa</a>
                                    <a class="btn btn-danger" href="@Url.Action("DeleteCourse","Course",new {ID = course.Id})">Xóa</a>
                                </td>
                            </tr>
                            i++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>


<script>
    $(document).ready(function () {
        $('#dataTabledata').DataTable();
    });
</script>

Views/HomeLecturer/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<partial name="_Notification" />

<h2>Index</h2>