Models/Lecturer.cs
using System;
using System.Collections.Generic;

namespace ILEARN.Models;

public partial class Lecturer
{
    public int Id { get; set; }

    public string LecturerName { get; set; } = null!;

    public string? Description { get; set; }

    public string Email { get; set; } = null!;

    public string Phone { get; set; } = null!;

    public string? Img { get; set; }

    public int AccountId { get; set; }

    public virtual Account Account { get; set; } = null!;

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}

Controllers/CourseController.cs
using ILEARN.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using System.Linq;
using System.Text;

namespace ILEARN.Controllers
{
    public class CourseController : Controller
    {
        public IActionResult Index(int? page)
        {
            using IlearnDbContext db = new();
            //var pageSize = 20;
            //var pageIndex = page ?? 1;
            var items = db.Courses.OrderBy(x => x.Id).ToList();
            return View(items);
        }

        public IActionResult GetCourse(int ID)
        {
            using IlearnDbContext db = new();
            var course = db.Courses.FirstOrDefault(m => m.Id == ID);
            if (course == null)
            {
                return RedirectToAction("NullPage", "Error");
            }
            else
            {
                return View(course);
            }
        }

        public IActionResult PriceIncreased(int? page)
        {
            using IlearnDbContext db = new();
            //var pageSize = 20;
            //var pageIndex = page ?? 1;
            var items = db.Courses.OrderBy(x => x.CoursePrice).ToList();
            return View(items);
        }

        public IActionResult PriceDecreased(int? page)
        {
            using IlearnDbContext db = new();
            //var pageSize = 20;
            //var pageIndex = page ?? 1;
            var items = db.Courses.OrderByDescending(x => x.CoursePrice).ToList();
            return View(items);
        }

        [HttpGet]
        public IActionResult Search(string search, int? page)
        {
            using IlearnDbContext db = new();
            //var pageSize = 20;
            //var pageIndex = page ?? 1;
            var items = db.Courses
                .AsEnumerable()
                .Where(c => RemoveDiacritics(c.CourseName.ToLower()).Contains(RemoveDiacritics(search.ToLower())))
                .OrderBy(c => c.Id)
                .ToList();
            TempData["count"] = items.Count;
            TempData["value"] = search;
            return View(items);
        }

        private static string RemoveDiacritics(string text)
        {
            var normalizedString = text.Normalize(NormalizationForm.FormD);
            var stringBuilder = new System.Text.StringBuilder();

            foreach (char c in normalizedString)
            {
                var unicodeCategory = CharUnicodeInfo.GetUnicodeCategory(c);
                if (unicodeCategory != UnicodeCategory.NonSpacingMark)
                {
                    stringBuilder.Append(c);
                }
            }

            return stringBuilder.ToString().Normalize(NormalizationForm.FormC);
        }

        public bool FunctionCheck(int functionID)
        {
            using IlearnDbContext db = new();
            var userName = TempData["user"]?.ToString()?.Trim();
            var gv = db.Accounts.First(item => item.Username == userName);
            if (gv != null)
            {
                int count = db.Decentralizations.Count(m => m.AccountId == gv.Id && m.FunctionId == functionID);
                if (count == 0)
                {
                    //báo không có quyền
                    return false;
                }
                else
                {
                    return true;
                }
            }

            return false;
        }

        public IActionResult CourseList()
        {
            if (FunctionCheck(5) == false)
            {
                //báo không có quyền
                return RedirectToAction("NoPrivilege", "Error");
            }

            using IlearnDbContext db = new IlearnDbContext();
            var courseList = db.Courses.Include(c => c.Lecturer).Include(c => c.Category).ToList();
            return View(courseList);
        }

        public IActionResult AddCourse()
        {
            if (FunctionCheck(6) == false)
            {
                //báo không có quyền
                return RedirectToAction("NoPrivilege", "Error");
            }

            return View();
        }

        [HttpPost]
        public IActionResult AddNewCourse(string name, decimal price, decimal discountPrice, int discount, int lecturesCount, string introduction, string description, int lecturerID, int categoryID)
        {
            IlearnDbContext db = new();
            Course course = new() { CourseName = name, CoursePrice = price, Description = description, DiscountPrice = discountPrice, Discount = discount, NumberOfLectures = lecturesCount, Introduction = introduction, LecturerId = lecturerID, CategoryId = categoryID };
            db.Courses.Add(course);
            db.SaveChanges();
            TempData["message"] = "Thêm thành công.";
            return RedirectToAction("CourseList");
        }

        public IActionResult UpdateCourse(int ID)
        {
            if (FunctionCheck(7) == false)
            {
                //báo không có quyền
                return RedirectToAction("NoPrivilege", "Error");
            }
            using IlearnDbContext db = new();
            var course = db.Courses.FirstOrDefault(m => m.Id == ID);
            return View(course);
        }

        [HttpPost]
        public IActionResult UpdateCurrentCourse(int ID, string name, decimal price, decimal discountPrice, int discount, int lecturesCount, string introduction, string description, int lecturerID, int categoryID)
        {
            using IlearnDbContext db = new();
            Course course = db.Courses.Find(ID);

            course.CourseName = name;
            course.CoursePrice = price;
            course.DiscountPrice = discountPrice;
            course.Discount = discount;
            course.NumberOfLectures = lecturesCount;
            course.Description = description;
            course.Introduction = introduction;
            course.LecturerId = lecturerID;
            course.CategoryId = categoryID;

            db.SaveChanges();

            TempData["message"] = "Cập nhật thành công.";
            return RedirectToAction("CourseList");
        }

        public IActionResult DeleteCourse(int ID)
        {
            if (FunctionCheck(8) == false)
            {
                //báo không có quyền
                return RedirectToAction("NoPrivilege", "Error");
            }

            using IlearnDbContext db = new();
            var course = db.Courses.Find(ID);
            db.Courses.Remove(course);
            db.SaveChanges();
            TempData["message"] = "Xóa thành công.";
            return RedirectToAction("CourseList");
        }

        public IActionResult MyCourse(int ID)
        {
            using IlearnDbContext db = new();
            var shoppingSession = db.ShoppingSessions.Where(m => m.AccountId == ID).ToList();
            List<int> courseList = new List<int>();
            if (shoppingSession != null)
            {
                foreach (var session in shoppingSession)
                {
                    var courses = db.Carts.Where(m => m.SessionId == session.Id)
                                            .Select(m => m.CourseId)
                                            .ToList();
                    courseList.AddRange(courses);
                }
                return View(courseList);
            }
            return View();
        }

        public IActionResult LearnThroughVideo()
        {
            using IlearnDbContext db = new IlearnDbContext();
            var videoList = db.Videos.Include(m=>m.Course).ToList();
            return View(videoList);
        }
    }
}

Controllers/LecturerController.cs
using ILEARN.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Drawing.Printing;

namespace ILEARN.Controllers
{
    public class LecturerController : Controller
    {
        public IActionResult Index(int ID)
        {
            using IlearnDbContext db = new();
            var lecturer = db.Lecturers.FirstOrDefault(m => m.Id == ID);
            return View(lecturer);
        }
        public bool FunctionCheck(int functionID)
        {
            using IlearnDbContext db = new();
            var userName = TempData["user"]?.ToString()?.Trim();
            var gv = db.Accounts.First(item => item.Username == userName);
            if (gv != null)
            {
                int count = db.Decentralizations.Count(m => m.AccountId == gv.Id && m.FunctionId == functionID);
                if (count == 0)
                {
                    //báo không có quyền
                    return false;
                }
                else
                {
                    return true;
                }
            }

            return false;
        }
        public IActionResult LecturerList()
        {
            if (FunctionCheck(1) == false)
            {
                //báo không có quyền
                return RedirectToAction("NoPrivilege", "Error");
            }

            using IlearnDbContext db = new();
            var items = db.Lecturers.Include(x => x.Account).Where(x => x.Account.Role == 2).OrderBy(x => x.Id).ToList();
            return View(items);
        }

        public IActionResult AddLecturer()
        {
            if (FunctionCheck(2) == false)
            {
                //báo không có quyền
                return RedirectToAction("NoPrivilege", "Error");
            }

            return View();
        }

        [HttpPost]
        [ActionName("AddNewLecturer")]
        public IActionResult AddNewLecturer(string name, string email, string description, string phone, string img)
        {
            IlearnDbContext db = new();
            Lecturer lecturer = new() { LecturerName = name, Email = email, Description = description, Phone = phone, Img = img };
            db.Lecturers.Add(lecturer);
            db.SaveChanges();
            TempData["message"] = "Thêm thành công.";
            return RedirectToAction("LecturerList");
        }

        public IActionResult UpdateLecturer(int ID)
        {
            if (FunctionCheck(3) == false)
            {
                //báo không có quyền
                return RedirectToAction("NoPrivilege", "Error");
            }
            using IlearnDbContext db = new();
            var lecturer = db.Lecturers.FirstOrDefault(m => m.Id == ID);
            return View(lecturer);
        }

        [HttpPost]
        public IActionResult UpdateCurrentLecturer(int ID, string name, string email, string description, string phone, string img)
        {
            using IlearnDbContext db = new();
            Lecturer lecturer = db.Lecturers.Find(ID);

            lecturer.Description = description;
            lecturer.Phone = phone;
            lecturer.Img = img;

            db.SaveChanges();

            TempData["message"] = "Cập nhật thành công.";
            return RedirectToAction("LecturerList");
        }

        public IActionResult DeleteLecturer(int ID)
        {
            if (FunctionCheck(4) == false)
            {
                //báo không có quyền
                return RedirectToAction("NoPrivilege", "Error");
            }

            using IlearnDbContext db = new();
            var lecturer = db.Lecturers.Find(ID);
            db.Lecturers.Remove(lecturer);
            db.SaveChanges();
            TempData["message"] = "Xoá thành công.";
            return RedirectToAction("LecturerList");
        }
    }
}

Views/Lecturer/AddLecturer.cshtml
@{
    ViewData["Title"] = "Thêm giảng viên";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Thêm giảng viên</h1>
                <form action="@Url.Action("AddNewLecturer","Lecturer")" method="post">
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <div class="col-md-2">
                            <label class="label-style">Tên giảng viên <span style="color: red">*</span></label>
                        </div>
                        <div class="col-md-10">
                            <input class="input-style input-sm" type="text" name="name" placeholder="Nhập tên giảng viên..." required/>
                        </div>
                    </div>
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <div class="col-md-2">
                            <label class="label-style">Email <span style="color: red">*</span></label>
                        </div>
                        <div class="col-md-10">
                            <input class="input-style input-sm" type="email" name="email" placeholder="Nhập email..." required/>
                        </div>                  
                    </div>
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <div class="col-md-2">
                            <label class="label-style">Chú thích</label>
                        </div>
                        <div class="col-md-10">
                            <textarea name="description" class="input-sm textarea-style ml-2" cols="100" rows="16" placeholder="Nhập chú thích..."></textarea>
                        </div>
                    </div>
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <div class="col-md-2">
                            <label class="label-style">Số điện thoại <span style="color: red">*</span></label>
                        </div>
                        <div class="col-md-10">
                            <input class="input-style input-sm" type="tel" name="phone" placeholder="Nhập số điện thoại..." required/>
                        </div>
                    </div>
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <div class="col-md-2">
                            <label class="label-style">Image Link</label>
                        </div>
                        <div class="col-md-10">
                            <input class="input-style input-sm" type="text" name="img" placeholder="Nhập image link..." />
                        </div>
                    </div>
                    <br />
                    <button class="btn btn-primary" type="submit">Xác nhận</button>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Lecturer/Index.cshtml
@using ILEARN.Models
@model ILEARN.Models.Lecturer

@{
    ViewData["Title"] = "Giảng viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="lecturer-section" class="minimal-border-full">
    <div style="height: 68px"> </div>
    <div class="lecturer-banner">
        <div class="container">
            <div class="row">
                <div class="container go-to-bottom">
                    <div class="row">
                        <div class="col-6">
                            <div class="row">
                                <div class="col-4">
                                    <img src="~/images/@Model.Img" class="rounded-circle minimal-border-full">
                                </div>
                                <div class="col-8 text-white">
                                    <h2 class="font-weight-bolder">@Model.LecturerName</h2>
                                    <p class="text-white">Giảng viên</p>
                                    <div class="social-list">
                                        <a class="social-button" href=""> <i class="fa fa-facebook-square"></i> Facebook </a>
                                        <a class="social-button" href=""> <i class="fa fa-youtube"></i> Youtube </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="ul-lecturer-detail float-right">
                                <ul>
                                    <li>
                                        <p class="text-white">@Common.GetCourseTeachedNumber(Model)</p>
                                        <span>Khóa học</span>
                                    </li>
                                    <li>
                                        <p class="text-white">0</p>
                                        <span>Học viên</span>
                                    </li>
                                    <li>
                                        <p class="text-white">0<i style="color: yellow" class="fa fa-star-o"></i></p>
                                        <span>Đánh giá trung bình</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="lecturer-detail minimal-border-bottom">
        <div class="container mt-4 mb-4">
            <h2 class="font-weight-bolder">Giới thiệu</h2>
            <p class="pre-line mt-2">@Model.Description</p>
        </div>
    </div>
    <div style="background: #F5F5F5" class="lecturer-relative-course pt-2 pb-2">
        <div class="container mt-4 mb-4">
            <h2 class="font-weight-bolder mb-4">Khóa học của giảng viên @Model.LecturerName</h2>
            @{
                foreach(Course j in Common.GetCourseTeachedByLecturer(Model))
                {
                    <div class="course-style minimal-border-full mt-2">
                        <div class="img-course-style minimal-border-full">
                            <a href="@Url.Action("GetCourse","Course", new {ID = j.Id})">
                                <img src="~/images/@j.Img" alt="@j.CourseName">
                            </a>
                        </div>
                        <div class="des-course-style">
                            <p>
                                <a href="@Url.Action("GetCourse","Course", new {ID = j.Id})" style="color: deepskyblue; font-weight: bold; font-size: 20px">@j.CourseName</a>
                            </p>
                            <ul class="d-inline-block text-black">
                                <li><i class="fas fa-list"></i> @j.NumberOfLectures bài giảng</li>
                                <li><i class="fa fa-clock-o"></i> 0</li>
                            </ul>
                            <p style="text-align: justify">@j.Introduction</p>
                        </div>
                        <div class="price-course-style">
                            <span class="price-n">@String.Format("{0: #,##0đ}", j.CoursePrice)</span>
                            <span class="price-t"><strike>@String.Format("{0: #,##0đ}", j.DiscountPrice)</strike></span>
                            <span class="price-d">off @j.Discount%</span>
                            <a class="minimal-border-full course-link-button" href="@Url.Action("GetCourse","Course", new {ID = j.Id})">CHI TIẾT</a>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

Views/Lecturer/LecturerList.cshtml
@model List<ILEARN.Models.Lecturer>
@using ILEARN.Models;

@{
    ViewData["Title"] = "Danh sách giảng viên";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<partial name="_Notification" />

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-header">Danh sách giảng viên</h1>
                <table class="table table-bordered" id="lecturerTable" style="font-size: 12px">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên giảng viên</th>
                            <th>Email</th>
                            <th>Chú thích</th>
                            <th>Số điện thoại</th>
                            <th>Image Link</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                            foreach (var l in Model)
                            {
                                    <tr>
                                        <td>@i</td>
                                        <td>@l.LecturerName</td>
                                        <td>@l.Email</td>
                                        <td>@l.Description</td>
                                        <td>@l.Phone</td>
                                        <td>@l.Img</td>
                                        <td>
                                            <a class="btn btn-info" href="@Url.Action("UpdateLecturer","Lecturer",new {ID = l.Id})">Sửa</a>
                                            <a class="btn btn-danger" onclick="showConfirmation(@l.Id)">Xóa</a>
                                        </td>
                                    </tr>
                                i++;
                            }
                        }
                    </tbody>                
                </table> 
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#lecturerTable').DataTable();
    })

    function showConfirmation(id) 
    { 
        var deleteUrl = '@Url.Action("DeleteLecturer", "Lecturer")';
        var result = window.confirm("Bạn có chắc muốn xóa không?");

        if (result) {
            var urlWithId = deleteUrl + '?ID=' + id;
            window.location.href = urlWithId;
        } 
    }
</script>

Views/Lecturer/UpdateLecturer.cshtml
@model ILEARN.Models.Lecturer

@{
    ViewData["Title"] = "Sửa giảng viên";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Sửa giảng viên</h1>
                <form action="@Url.Action("UpdateCurrentLecturer","Lecturer", new {ID = Model.Id})" method="post">
                    <input type="text" name="ID" value="@Model.Id" hidden/>
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <div class="col-md-2">
                            <label class="label-style">Tên giảng viên <span style="color: red">*</span></label>
                        </div>
                        <div class="col-md-10">
                            <input class="input-style input-lg" type="text" name="name" placeholder="Nhập tên giảng viên..." value="@Model.LecturerName"/>
                        </div>
                    </div>
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <div class="col-md-2">
                            <label class="label-style">Email <span style="color: red">*</span></label>
                        </div>
                        <div class="col-md-10">
                            <input class="input-style input-lg" type="email" name="email" placeholder="Nhập email..." value="@Model.Email" disabled/>
                        </div>
                    </div>
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <div class="col-md-2">
                            <label class="label-style">Chú thích</label>
                        </div>
                        <div class="col-md-10">
                            <textarea name="description" class="description textarea-style ml-2" cols="100" rows="16" placeholder="Nhập chú thích...">@Model.Description</textarea>
                        </div>
                    </div>
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <div class="col-md-2">
                            <label class="label-style">Số điện thoại <span style="color: red">*</span></label>
                        </div>
                        <div class="col-md-10">
                            <input class="input-style input-lg" type="tel" name="phone" placeholder="Nhập số điện thoại..." value="@Model.Phone" />
                        </div>
                    </div>
                    <div class="row mb-2" style="margin-bottom: 20px">
                        <div class="col-md-2">
                            <label class="label-style">Image Link</label>
                        </div>
                        <div class="col-md-10">
                            <input class="input-style input-lg" type="text" name="img" placeholder="Nhập image link..." value="@Model.Img" />
                        </div>
                    </div>
                    <br />
                    <button class="btn btn-primary" type="submit">Xác nhận</button>
                </form>
            </div>
        </div>
    </div>
</div>