Models/Decentralization.cs
using System;
using System.Collections.Generic;

namespace ILEARN.Models;

public partial class Decentralization
{
    public int Id { get; set; }

    public int AccountId { get; set; }

    public int FunctionId { get; set; }

    public virtual Account Account { get; set; } = null!;

    public virtual FunctionT Function { get; set; } = null!;
}

Models/DecentralizationViewModel.cs
namespace ILEARN.Models
{
    public class DecentralizationViewModel
    {
        public int AccountID { get; set; }
        public string LecturerName { get; set; }
        public Dictionary<int, bool> FunctionPermissions { get; set; }

        public DecentralizationViewModel()
        {
            FunctionPermissions = new Dictionary<int, bool>();
        }
    }

}

Controllers/HomeAdminController.cs
using Azure.Core;
using ILEARN.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace ILEARN.Controllers
{
    public class HomeAdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Transaction()
        {
            using IlearnDbContext db = new IlearnDbContext();
            var shoppingSession = db.ShoppingSessions.Include(c => c.Carts).Include(c => c.Account).ToList();
            return View(shoppingSession);
        }

        public IActionResult GetShoppingSessionDetails(int ID)
        {
            using IlearnDbContext db = new IlearnDbContext();
            var cartDetail = db.Carts.Include(m => m.Course).Where(m => m.SessionId == ID).ToList();
            return View(cartDetail);
        }

        public IActionResult Decentralization()
        {
            using (IlearnDbContext db = new IlearnDbContext())
            {
                List<Lecturer> lecturers = db.Lecturers
                    .Include(l => l.Account)
                    .Where(l => l.Account.Role == 2)
                    .ToList();

                List<FunctionT> functions = db.FunctionTs.Where(f => !f.FunctionName.Contains("Tài khoản:") && !f.FunctionName.Contains("Giảng viên:")).ToList();
                List<Decentralization> decentralizations = db.Decentralizations.ToList();
                List<DecentralizationViewModel> viewModelList = new List<DecentralizationViewModel>();

                // Iterate through each lecturer
                foreach (var lecturer in lecturers)
                {
                    var viewModel = new DecentralizationViewModel
                    {
                        AccountID = lecturer.AccountId,
                        LecturerName = lecturer.LecturerName
                    };

                    foreach (var function in functions)
                    {
                        var decentralization = decentralizations.FirstOrDefault(d => d.AccountId == lecturer.AccountId && d.FunctionId == function.Id);
                        viewModel.FunctionPermissions.Add(function.Id, decentralization != null);
                    }
                    viewModelList.Add(viewModel);
                }
                return View(viewModelList);
            }
        }


        [HttpPost]
        public IActionResult UpdateDecentralization(int accountId, int functionId, bool isChecked)
        {
            using IlearnDbContext db = new IlearnDbContext();
            if (isChecked)
            {
                var newDecentralization = new Decentralization
                {
                    AccountId = accountId,
                    FunctionId = functionId
                };
                db.Decentralizations.Add(newDecentralization);
            }
            else
            {
                var existingDecentralization = db.Decentralizations
                    .FirstOrDefault(d => d.AccountId == accountId && d.FunctionId == functionId);

                if (existingDecentralization != null)
                {
                    db.Decentralizations.Remove(existingDecentralization);
                }
            }

            db.SaveChanges();

            return Ok();
        }

        [HttpPost]
        public ActionResult Report(int year)
        {
            using IlearnDbContext db = new();
            var data = db.ShoppingSessions
                .Where(session => session.CreatedAt.Year == year)
                .GroupBy(session => session.CreatedAt.Month)
                .Select(group => new
                {
                    y = group.Key.ToString(),
                    a = group.Sum(session => session.Total)
                })
                .ToList();

            return Json(data);
        }
    }
}

Views/HomeAdmin/Decentralization.cshtml
@model List<DecentralizationViewModel>
@{
    ViewData["Title"] = "Phân quyền";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-header">Phân quyền giảng viên</h1>
                <table class="table table-bordered" id="deTable">
                    <thead>
                        <tr>
                            <th>Tên giảng viên</th>
                            @{
                                using IlearnDbContext db = new IlearnDbContext();
                                foreach (var function in Model.FirstOrDefault()?.FunctionPermissions ?? new Dictionary<int, bool>())
                                {
                                        <th>@db.FunctionTs.Find(function.Key).FunctionName</th>
                                }
                            }
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var viewModel in Model)
                        {
                            <tr>
                                <td>@viewModel.LecturerName</td>
                                @foreach (var functionPermission in viewModel.FunctionPermissions)
                                {
                                    <td>
                                        <input type="checkbox"
                                               id=""
                                                @(functionPermission.Value ? "checked" : "")
                                               onclick="updateDecentralization(@viewModel.AccountID, @functionPermission.Key, this.checked)" />
                                    </td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#deTable').DataTable();
    })
</script>

<script>
    function updateDecentralization(accountId, functionId, isChecked) {
        $.ajax({
            type: "POST",
            url: "/HomeAdmin/UpdateDecentralization",
            data: {
                accountId: accountId,
                functionId: functionId,
                isChecked: isChecked
            },
            success: function (data) {
            },
            error: function (error) {
                console.error("Error updating Decentralization:", error);
            }
        });
    }
</script>

Views/HomeAdmin/GetShoppingSessionDetails.cshtml
@{
    ViewData["Title"] = "GetShoppingSessionDetails";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

@model List<ILEARN.Models.Cart>
@using ILEARN.Models;

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-header">Chi tiết giao dịch</h1>
                <table class="table table-bordered" id="transactionDetailsTable" style="font-size: 12px">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Khóa học</th>
                            <th>Giá</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@item.Course.CourseName</td>
                                    <td>@String.Format("{0: #,##0đ}", item.Course.DiscountPrice)</td>
                                </tr>
                                i++;
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#transactionDetailsTable').DataTable();
    })
</script>

Views/HomeAdmin/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<partial name="_Notification" />

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Thống kê doanh thu</h1>
                <div class="row">
                    <div class="col-sm-6 text-center">
                        <label class="label label-success">Chọn tháng và năm:</label>
                        <input type="text" id="selectedMonthYear" class="form-control">
                        <br>
                        <button id="updateChartBtn" class="btn btn-primary">Cập nhật biểu đồ</button>
                        <br><br>
                        <div id="bar-chart"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $('#selectedMonthYear').datepicker({
            changeMonth: false,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'yy', // Display format for month and year
            onClose: function (dateText, inst) {
                updateChart();
            }
        });

        // Initial chart load with default selected month and year
        updateChart();

        // Update chart when the button is clicked
        $('#updateChartBtn').click(function () {
            updateChart();
        });

        function updateChart() {
            var selectedYear = $('#selectedMonthYear').val();

            $.ajax({
                url: '@Url.Action("Report", "HomeAdmin")',
                method: 'POST',
                data: { year: selectedYear }, // Send the selected year to the server
                success: function (data) {
                    Morris.Bar({
                        element: 'bar-chart',
                        data: data,
                        xkey: 'month', // Assuming 'month' is the property for the X-axis
                        ykeys: ['total'],
                        labels: ['Total Income'],
                        fillOpacity: 0.6,
                        hideHover: 'auto',
                        behaveLikeLine: true,
                        resize: true,
                        pointFillColors: ['#ffffff'],
                        pointStrokeColors: ['black'],
                        barColors: ['#3498db'], // Adjust the color as needed
                    });
                },
                error: function (xhr, status, error) {
                    console.error(xhr.responseText);
                }
            });
        }
    }); // Add this closing parenthesis
</script>

Views/HomeAdmin/Transaction.cshtml
@{
    ViewData["Title"] = "Transaction";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

@model List<ILEARN.Models.ShoppingSession>
@using ILEARN.Models;

@{
    ViewData["Title"] = "Danh sách giao dịch";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-header">Danh sách giao dịch</h1>
                <table class="table table-bordered" id="transactionTable" style="font-size: 12px">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Mã giao dịch</th>
                            <th>Tên học sinh</th>
                            <th>Ngày giao dịch</th>
                            <th>Tổng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                            foreach (var l in Model)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td>
                                        <a href="@Url.Action("GetShoppingSessionDetails","HomeAdmin",new{ID = l.Id})">
                                            <span>T00</span>@l.Id
                                        </a>
                                    </td>
                                    <td>@Common.GetStudentByID(l.AccountId).Name</td>
                                    <td>@l.CreatedAt.ToString("MM/dd/yyyy HH:mm")</td>
                                    <td>@String.Format("{0: #,##0đ}",@l.Total)</td>
                                </tr>
                                i++;
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#transactionTable').DataTable();
    })
</script>